In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("heart.csv")

In [4]:
df = df.sample(frac = 1)

In [5]:
i = 5

In [6]:
inp = df.iloc[:,:-1]
inp

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
128,52,0,2,136,196,0,0,169,0,0.1,1,0,2
199,65,1,0,110,248,0,0,158,0,0.6,2,2,1
223,56,0,0,200,288,1,0,133,1,4.0,0,2,3
116,41,1,2,130,214,0,0,168,0,2.0,1,0,2
17,66,0,3,150,226,0,1,114,0,2.6,0,0,2
265,66,1,0,112,212,0,0,132,1,0.1,2,1,2
125,34,0,1,118,210,0,1,192,0,0.7,2,0,2
287,57,1,1,154,232,0,0,164,0,0.0,2,1,2
114,55,1,1,130,262,0,1,155,0,0.0,2,0,2
25,71,0,1,160,302,0,1,162,0,0.4,2,2,2
81,45,1,1,128,308,0,0,170,0,0.0,2,0,2
68,44,1,1,120,220,0,1,170,0,0.0,2,0,2
80,41,1,2,112,250,0,1,179,0,0.0,2,0,2
146,44,0,2,118,242,0,1,149,0,0.3,1,1,2
188,50,1,2,140,233,0,1,163,0,0.6,1,1,3
166,67,1,0,120,229,0,0,129,1,2.6,1,2,3
137,62,1,1,128,208,1,0,140,0,0.0,2,0,2
212,39,1,0,118,219,0,1,140,0,1.2,1,0,3
244,56,1,0,132,184,0,0,105,1,2.1,1,1,1
24,40,1,3,140,199,0,1,178,1,1.4,2,0,3
98,43,1,2,130,315,0,1,162,0,1.9,2,1,2
184,50,1,0,150,243,0,0,128,0,2.6,1,0,3
79,58,1,2,105,240,0,0,154,1,0.6,1,0,3
258,62,0,0,150,244,0,1,154,1,1.4,1,0,2
219,48,1,0,130,256,1,0,150,1,0.0,2,2,3
89,58,0,0,100,248,0,0,122,0,1.0,1,0,2
168,63,1,0,130,254,0,0,147,0,1.4,1,1,3
274,47,1,0,110,275,0,0,118,1,1.0,1,1,2
16,58,0,2,120,340,0,1,172,0,0.0,2,0,2
261,52,1,0,112,230,0,1,160,0,0.0,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13,64,1,3,110,211,0,0,144,1,1.8,1,0,2
50,51,0,2,130,256,0,0,149,0,0.5,2,0,2
93,54,0,1,132,288,1,0,159,1,0.0,2,1,2
197,67,1,0,125,254,1,1,163,0,0.2,1,2,3
257,50,1,0,144,200,0,0,126,1,0.9,1,0,3
297,59,1,0,164,176,1,0,90,0,1.0,1,2,1
70,54,1,2,120,258,0,0,147,0,0.4,1,0,3
228,59,1,3,170,288,0,0,159,0,0.2,1,0,3
230,47,1,2,108,243,0,1,152,0,0.0,2,0,2
231,57,1,0,165,289,1,0,124,0,1.0,1,3,3
85,67,0,2,115,564,0,0,160,0,1.6,1,0,3
154,39,0,2,138,220,0,1,152,0,0.0,1,0,2
191,58,1,0,128,216,0,0,131,1,2.2,1,3,3
104,50,1,2,129,196,0,1,163,0,0.0,2,0,2
268,54,1,0,122,286,0,0,116,1,3.2,1,2,2
29,53,1,2,130,197,1,0,152,0,1.2,0,0,2
65,35,0,0,138,183,0,1,182,0,1.4,2,0,2
173,58,1,2,132,224,0,0,173,0,3.2,2,2,3
99,53,1,2,130,246,1,0,173,0,0.0,2,3,2
95,53,1,0,142,226,0,0,111,1,0.0,2,0,3
238,77,1,0,125,304,0,0,162,1,0.0,2,3,2
132,42,1,1,120,295,0,1,162,0,0.0,2,0,2
39,65,0,2,160,360,0,0,151,0,0.8,2,0,2
249,69,1,2,140,254,0,0,146,0,2.0,1,3,3
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3
107,45,0,0,138,236,0,0,152,1,0.2,1,0,2
165,67,1,0,160,286,0,0,108,1,1.5,1,3,2
176,60,1,0,117,230,1,1,160,1,1.4,2,2,3
189,41,1,0,110,172,0,0,158,0,0.0,2,0,3
150,66,1,0,160,228,0,0,138,0,2.3,2,0,1

In [8]:
out = df.iloc[:, -1]
out

128    1
199    0
223    0
116    1
17     1
265    0
125    1
287    0
114    1
25     1
81     1
68     1
80     1
146    1
188    0
166    0
137    1
212    0
244    0
24     1
98     1
184    0
79     1
258    0
219    0
89     1
168    0
274    0
16     1
261    0
      ..
13     1
50     1
93     1
197    0
257    0
297    0
70     1
228    0
230    0
231    0
85     1
154    1
191    0
104    1
268    0
29     1
65     1
173    0
99     1
95     1
238    0
132    1
39     1
249    0
299    0
107    1
165    0
176    0
189    0
150    1
Name: target, Length: 303, dtype: int64

In [8]:
n = len(df)

In [9]:
n

303

In [9]:
train_x = inp[:250]
train_x

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
128,52,0,2,136,196,0,0,169,0,0.1,1,0,2
199,65,1,0,110,248,0,0,158,0,0.6,2,2,1
223,56,0,0,200,288,1,0,133,1,4.0,0,2,3
116,41,1,2,130,214,0,0,168,0,2.0,1,0,2
17,66,0,3,150,226,0,1,114,0,2.6,0,0,2
265,66,1,0,112,212,0,0,132,1,0.1,2,1,2
125,34,0,1,118,210,0,1,192,0,0.7,2,0,2
287,57,1,1,154,232,0,0,164,0,0.0,2,1,2
114,55,1,1,130,262,0,1,155,0,0.0,2,0,2
25,71,0,1,160,302,0,1,162,0,0.4,2,2,2
81,45,1,1,128,308,0,0,170,0,0.0,2,0,2
68,44,1,1,120,220,0,1,170,0,0.0,2,0,2
80,41,1,2,112,250,0,1,179,0,0.0,2,0,2
146,44,0,2,118,242,0,1,149,0,0.3,1,1,2
188,50,1,2,140,233,0,1,163,0,0.6,1,1,3
166,67,1,0,120,229,0,0,129,1,2.6,1,2,3
137,62,1,1,128,208,1,0,140,0,0.0,2,0,2
212,39,1,0,118,219,0,1,140,0,1.2,1,0,3
244,56,1,0,132,184,0,0,105,1,2.1,1,1,1
24,40,1,3,140,199,0,1,178,1,1.4,2,0,3
98,43,1,2,130,315,0,1,162,0,1.9,2,1,2
184,50,1,0,150,243,0,0,128,0,2.6,1,0,3
79,58,1,2,105,240,0,0,154,1,0.6,1,0,3
258,62,0,0,150,244,0,1,154,1,1.4,1,0,2
219,48,1,0,130,256,1,0,150,1,0.0,2,2,3
89,58,0,0,100,248,0,0,122,0,1.0,1,0,2
168,63,1,0,130,254,0,0,147,0,1.4,1,1,3
274,47,1,0,110,275,0,0,118,1,1.0,1,1,2
16,58,0,2,120,340,0,1,172,0,0.0,2,0,2
261,52,1,0,112,230,0,1,160,0,0.0,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
33,54,1,2,125,273,0,0,152,0,0.5,0,1,2
262,53,1,0,123,282,0,1,95,1,2.0,1,2,3
82,60,0,2,102,318,0,1,160,0,0.0,2,1,2
83,52,1,3,152,298,1,1,178,0,1.2,1,0,3
222,65,1,3,138,282,1,0,174,0,1.4,1,1,2
278,58,0,1,136,319,1,0,152,0,0.0,2,2,2
213,61,0,0,145,307,0,0,146,1,1.0,1,0,3
141,43,1,0,115,303,0,1,181,0,1.2,1,0,2
152,64,1,3,170,227,0,0,155,0,0.6,1,0,3
103,42,1,2,120,240,1,1,194,0,0.8,0,0,3
27,51,1,2,110,175,0,1,123,0,0.6,2,0,2
22,42,1,0,140,226,0,1,178,0,0.0,2,0,2
11,48,0,2,130,275,0,1,139,0,0.2,2,0,2
84,42,0,0,102,265,0,0,122,0,0.6,1,0,2
248,54,1,1,192,283,0,0,195,0,0.0,2,1,3
205,52,1,0,128,255,0,1,161,1,0.0,2,1,3
14,58,0,3,150,283,1,0,162,0,1.0,2,0,2
282,59,1,2,126,218,1,1,134,0,2.2,1,1,1
66,51,1,2,100,222,0,1,143,1,1.2,1,0,2
221,55,1,0,140,217,0,1,111,1,5.6,0,0,3
30,41,0,1,105,198,0,1,168,0,0.0,2,1,2
229,64,1,2,125,309,0,1,131,1,1.8,1,0,3
204,62,0,0,160,164,0,0,145,0,6.2,0,3,3
5,57,1,0,140,192,0,1,148,0,0.4,1,0,1
34,51,1,3,125,213,0,0,125,1,1.4,2,1,2
31,65,1,0,120,177,0,1,140,0,0.4,2,0,3
215,43,0,0,132,341,1,0,136,1,3.0,1,0,3
245,48,1,0,124,274,0,0,166,0,0.5,1,0,3
151,71,0,0,112,149,0,1,125,0,1.6,1,0,2
160,56,1,1,120,240,0,1,169,0,0.0,0,0,2

In [15]:
test_x = inp[250:]
test_x

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
44,39,1,2,140,321,0,0,182,0,0.0,2,0,2
92,52,1,2,138,223,0,1,169,0,0.0,2,4,2
270,46,1,0,120,249,0,0,144,0,0.8,2,0,3
239,35,1,0,126,282,0,0,156,1,0.0,2,0,3
212,39,1,0,118,219,0,1,140,0,1.2,1,0,3
10,54,1,0,140,239,0,1,160,0,1.2,2,0,2
39,65,0,2,160,360,0,0,151,0,0.8,2,0,2
5,57,1,0,140,192,0,1,148,0,0.4,1,0,1
194,60,1,2,140,185,0,0,155,0,3.0,1,0,2
175,40,1,0,110,167,0,0,114,1,2.0,1,0,3
120,64,0,0,130,303,0,1,122,0,2.0,1,2,2
244,56,1,0,132,184,0,0,105,1,2.1,1,1,1
134,41,0,1,126,306,0,1,163,0,0.0,2,0,2
152,64,1,3,170,227,0,0,155,0,0.6,1,0,3
176,60,1,0,117,230,1,1,160,1,1.4,2,2,3
95,53,1,0,142,226,0,0,111,1,0.0,2,0,3
43,53,0,0,130,264,0,0,143,0,0.4,1,0,2
70,54,1,2,120,258,0,0,147,0,0.4,1,0,3
87,46,1,1,101,197,1,1,156,0,0.0,2,0,3
163,38,1,2,138,175,0,1,173,0,0.0,2,4,2
200,44,1,0,110,197,0,0,177,0,0.0,2,1,2
253,67,1,0,100,299,0,0,125,1,0.9,1,2,2
274,47,1,0,110,275,0,0,118,1,1.0,1,1,2
69,62,0,0,124,209,0,1,163,0,0.0,2,0,2
265,66,1,0,112,212,0,0,132,1,0.1,2,1,2
119,46,0,0,138,243,0,0,152,1,0.0,1,0,2
32,44,1,1,130,219,0,0,188,0,0.0,2,0,2
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3
144,76,0,2,140,197,0,2,116,0,1.1,1,0,2
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
68,44,1,1,120,220,0,1,170,0,0.0,2,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
146,44,0,2,118,242,0,1,149,0,0.3,1,1,2
59,57,0,0,128,303,0,0,159,0,0.0,2,1,2
278,58,0,1,136,319,1,0,152,0,0.0,2,2,2
140,51,0,2,120,295,0,0,157,0,0.6,2,0,2
272,67,1,0,120,237,0,1,71,0,1.0,1,0,2
259,38,1,3,120,231,0,1,182,1,3.8,1,0,3
193,60,1,0,145,282,0,0,142,1,2.8,1,2,3
54,63,0,2,135,252,0,0,172,0,0.0,2,0,2
8,52,1,2,172,199,1,1,162,0,0.5,2,0,3
133,41,1,1,110,235,0,1,153,0,0.0,2,0,2
118,46,0,1,105,204,0,1,172,0,0.0,2,0,2
61,54,1,1,108,309,0,1,156,0,0.0,2,0,3
7,44,1,1,120,263,0,1,173,0,0.0,2,0,3
238,77,1,0,125,304,0,0,162,1,0.0,2,3,2
124,39,0,2,94,199,0,1,179,0,0.0,2,0,2
31,65,1,0,120,177,0,1,140,0,0.4,2,0,3
125,34,0,1,118,210,0,1,192,0,0.7,2,0,2
93,54,0,1,132,288,1,0,159,1,0.0,2,1,2
15,50,0,2,120,219,0,1,158,0,1.6,1,0,2
202,58,1,0,150,270,0,0,111,1,0.8,2,0,3
275,52,1,0,125,212,0,1,168,0,1.0,2,2,3

In [38]:
train_y = out[:250]
train_y

195    0
166    0
74     1
115    1
199    0
1      1
277    0
296    0
287    0
243    0
224    0
11     1
111    1
289    0
57     1
65     1
246    0
211    0
295    0
40     1
66     1
232    0
216    0
91     1
84     1
71     1
30     1
213    0
248    0
252    0
      ..
109    1
110    1
229    0
85     1
148    1
47     1
197    0
191    0
63     1
45     1
143    1
279    0
167    0
123    1
177    0
285    0
46     1
108    1
62     1
173    0
107    1
255    0
228    0
263    0
208    0
17     1
231    0
55     1
50     1
136    1
Name: target, Length: 250, dtype: int64

In [39]:
test_y = out[250:]
test_y

44     1
92     1
270    0
239    0
212    0
10     1
39     1
5      1
194    0
175    0
120    1
244    0
134    1
152    1
176    0
95     1
43     1
70     1
87     1
163    1
200    0
253    0
274    0
69     1
265    0
119    1
32     1
301    0
144    1
0      1
68     1
2      1
146    1
59     1
278    0
140    1
272    0
259    0
193    0
54     1
8      1
133    1
118    1
61     1
7      1
238    0
124    1
31     1
125    1
93     1
15     1
202    0
275    0
Name: target, dtype: int64

In [16]:
dis((0, 0), (1, 1))

1.4142135623730951

In [34]:
import math
def dis(t1, t2):
    sum = 0
    for i in range(len(t1)):
        sum += (t1[i] - t2[i])**2
        print('t1',t1,t2,sum,i)
    return math.sqrt(sum)

In [35]:
dis((3,4),(2,2))

t1 (3, 4) (2, 2) 1 0
t1 (3, 4) (2, 2) 5 1

2.23606797749979

In [36]:
def knn():
    tpl = []
    for j in range(len(train_x)):
        tpl.append((dis(train_x.iloc[j], test_x.iloc[i]), j))
        print(test_x.iloc[i],len(train_x))
    return tpl

In [42]:
# knn()
for j in range(len(train_x)):
    print(train_x.iloc[j], test_x.iloc[i])

age          59.0
sex           1.0
cp            0.0
trestbps    170.0
chol        326.0
fbs           0.0
restecg       0.0
thalach     140.0
exang         1.0
oldpeak       3.4
slope         0.0
ca            0.0
thal          3.0
Name: 195, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          67.0
sex           1.0
cp            0.0
trestbps    120.0
chol        229.0
fbs           0.0
restecg       0.0
thalach     129.0
exang         1.0
oldpeak       2.6
slope         1.0
ca            2.0
thal          3.0
Name: 166, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          43.0
sex           0.0
cp            2.0
trestbps    122.0
chol        213.0
fbs           0.0
restecg       1.0
thalach     165.0
exang         0.0
oldpeak       0.2
slope         1.0
ca            0.0
thal          2.0
Name: 74, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          37.0
sex           0.0
cp            2.0
trestbps    120.0
chol        215.0
fbs           0.0
restecg       1.0
thalach     170.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          2.0
Name: 115, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          65.0
sex           1.0
cp            0.0
trestbps    110.0
chol        248.0
fbs           0.0
restecg       0.0
thalach     158.0
exang         0.0
oldpeak       0.6
slope         2.0
ca            2.0
thal          1.0
Name: 199, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          37.0
sex           1.0
cp            2.0
trestbps    130.0
chol        250.0
fbs           0.0
restecg       1.0
thalach     187.0
exang         0.0
oldpeak       3.5
slope         0.0
ca            0.0
thal          2.0
Name: 1, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          57.0
sex           1.0
cp            1.0
trestbps    124.0
chol        261.0
fbs           0.0
restecg       1.0
thalach     141.0
exang         0.0
oldpeak       0.3
slope         2.0
ca            0.0
thal          3.0
Name: 277, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          63.0
sex           0.0
cp            0.0
trestbps    124.0
chol        197.0
fbs           0.0
restecg       1.0
thalach     136.0
exang         1.0
oldpeak       0.0
slope         1.0
ca            0.0
thal          2.0
Name: 296, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          57.0
sex           1.0
cp            1.0
trestbps    154.0
chol        232.0
fbs           0.0
restecg       0.0
thalach     164.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            1.0
thal          2.0
Name: 287, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          57.0
sex           1.0
cp            0.0
trestbps    152.0
chol        274.0
fbs           0.0
restecg       1.0
thalach      88.0
exang         1.0
oldpeak       1.2
slope         1.0
ca            1.0
thal          3.0
Name: 243, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          54.0
sex           1.0
cp            0.0
trestbps    110.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     126.0
exang         1.0
oldpeak       2.8
slope         1.0
ca            1.0
thal          3.0
Name: 224, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          48.0
sex           0.0
cp            2.0
trestbps    130.0
chol        275.0
fbs           0.0
restecg       1.0
thalach     139.0
exang         0.0
oldpeak       0.2
slope         2.0
ca            0.0
thal          2.0
Name: 11, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          57.0
sex           1.0
cp            2.0
trestbps    150.0
chol        126.0
fbs           1.0
restecg       1.0
thalach     173.0
exang         0.0
oldpeak       0.2
slope         2.0
ca            1.0
thal          3.0
Name: 111, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          55.0
sex           0.0
cp            0.0
trestbps    128.0
chol        205.0
fbs           0.0
restecg       2.0
thalach     130.0
exang         1.0
oldpeak       2.0
slope         1.0
ca            1.0
thal          3.0
Name: 289, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          45.0
sex           1.0
cp            0.0
trestbps    115.0
chol        260.0
fbs           0.0
restecg       0.0
thalach     185.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          2.0
Name: 57, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          35.0
sex           0.0
cp            0.0
trestbps    138.0
chol        183.0
fbs           0.0
restecg       1.0
thalach     182.0
exang         0.0
oldpeak       1.4
slope         2.0
ca            0.0
thal          2.0
Name: 65, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          56.0
sex           0.0
cp            0.0
trestbps    134.0
chol        409.0
fbs           0.0
restecg       0.0
thalach     150.0
exang         1.0
oldpeak       1.9
slope         1.0
ca            2.0
thal          3.0
Name: 246, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          61.0
sex           1.0
cp            0.0
trestbps    120.0
chol        260.0
fbs           0.0
restecg       1.0
thalach     140.0
exang         1.0
oldpeak       3.6
slope         1.0
ca            1.0
thal          3.0
Name: 211, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          63.0
sex           1.0
cp            0.0
trestbps    140.0
chol        187.0
fbs           0.0
restecg       0.0
thalach     144.0
exang         1.0
oldpeak       4.0
slope         2.0
ca            2.0
thal          3.0
Name: 295, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          51.0
sex           0.0
cp            2.0
trestbps    140.0
chol        308.0
fbs           0.0
restecg       0.0
thalach     142.0
exang         0.0
oldpeak       1.5
slope         2.0
ca            1.0
thal          2.0
Name: 40, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          51.0
sex           1.0
cp            2.0
trestbps    100.0
chol        222.0
fbs           0.0
restecg       1.0
thalach     143.0
exang         1.0
oldpeak       1.2
slope         1.0
ca            0.0
thal          2.0
Name: 66, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          55.0
sex           1.0
cp            0.0
trestbps    160.0
chol        289.0
fbs           0.0
restecg       0.0
thalach     145.0
exang         1.0
oldpeak       0.8
slope         1.0
ca            1.0
thal          3.0
Name: 232, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          62.0
sex           0.0
cp            2.0
trestbps    130.0
chol        263.0
fbs           0.0
restecg       1.0
thalach      97.0
exang         0.0
oldpeak       1.2
slope         1.0
ca            1.0
thal          3.0
Name: 216, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          57.0
sex           1.0
cp            0.0
trestbps    132.0
chol        207.0
fbs           0.0
restecg       1.0
thalach     168.0
exang         1.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          3.0
Name: 91, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          42.0
sex           0.0
cp            0.0
trestbps    102.0
chol        265.0
fbs           0.0
restecg       0.0
thalach     122.0
exang         0.0
oldpeak       0.6
slope         1.0
ca            0.0
thal          2.0

Name: 84, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          51.0
sex           1.0
cp            2.0
trestbps     94.0
chol        227.0
fbs           0.0
restecg       1.0
thalach     154.0
exang         1.0
oldpeak       0.0
slope         2.0
ca            1.0
thal          3.0
Name: 71, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          41.0
sex           0.0
cp            1.0
trestbps    105.0
chol        198.0
fbs           0.0
restecg       1.0
thalach     168.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            1.0
thal          2.0
Name: 30, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          61.0
sex           0.0
cp            0.0
trestbps    145.0
chol        307.0
fbs           0.0
restecg       0.0
thalach     146.0
exang         1.0
oldpeak       1.0
slope         1.0
ca            0.0
thal          3.0
Name: 213, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          54.0
sex           1.0
cp            1.0
trestbps    192.0
chol        283.0
fbs           0.0
restecg       0.0
thalach     195.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            1.0
thal          3.0
Name: 248, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          62.0
sex           0.0
cp            0.0
trestbps    138.0
chol        294.0
fbs           1.0
restecg       1.0
thalach     106.0
exang         0.0
oldpeak       1.9
slope         1.0
ca            3.0
thal          2.0
Name: 252, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          57.0
sex           1.0
cp            0.0
trestbps    150.0
chol        276.0
fbs           0.0
restecg       0.0
thalach     112.0
exang         1.0
oldpeak       0.6
slope         1.0
ca            1.0
thal          1.0
Name: 179, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          52.0
sex           0.0
cp            2.0
trestbps    136.0
chol        196.0
fbs           0.0
restecg       0.0
thalach     169.0
exang         0.0
oldpeak       0.1
slope         1.0
ca            0.0
thal          2.0
Name: 128, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          44.0
sex           1.0
cp            0.0
trestbps    112.0
chol        290.0
fbs           0.0
restecg       0.0
thalach     153.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            1.0
thal          2.0
Name: 185, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          49.0
sex           0.0
cp            0.0
trestbps    130.0
chol        269.0
fbs           0.0
restecg       1.0
thalach     163.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          2.0
Name: 135, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          51.0
sex           1.0
cp            0.0
trestbps    140.0
chol        261.0
fbs           0.0
restecg       0.0
thalach     186.0
exang         1.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          2.0
Name: 73, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          59.0
sex           1.0
cp            0.0
trestbps    140.0
chol        177.0
fbs           0.0
restecg       1.0
thalach     162.0
exang         1.0
oldpeak       0.0
slope         2.0
ca            1.0
thal          3.0
Name: 209, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          61.0
sex           1.0
cp            2.0
trestbps    150.0
chol        243.0
fbs           1.0
restecg       1.0
thalach     137.0
exang         1.0
oldpeak       1.0
slope         1.0
ca            0.0
thal          2.0
Name: 23, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          56.0
sex           0.0
cp            0.0
trestbps    200.0
chol        288.0
fbs           1.0
restecg       0.0
thalach     133.0
exang         1.0
oldpeak       4.0
slope         0.0
ca            2.0
thal          3.0
Name: 223, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          70.0
sex           1.0
cp            0.0
trestbps    130.0
chol        322.0
fbs           0.0
restecg       0.0
thalach     109.0
exang         0.0
oldpeak       2.4
slope         1.0
ca            3.0
thal          2.0
Name: 234, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          58.0
sex           1.0
cp            1.0
trestbps    125.0
chol        220.0
fbs           0.0
restecg       1.0
thalach     144.0
exang         0.0
oldpeak       0.4
slope         1.0
ca            4.0
thal          3.0
Name: 158, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          58.0
sex           0.0
cp            0.0
trestbps    130.0
chol        197.0
fbs           0.0
restecg       1.0
thalach     131.0
exang         0.0
oldpeak       0.6
slope         1.0
ca            0.0
thal          2.0
Name: 155, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          49.0
sex           1.0
cp            2.0
trestbps    118.0
chol        149.0
fbs           0.0
restecg       0.0
thalach     126.0
exang         0.0
oldpeak       0.8
slope         2.0
ca            3.0
thal          2.0
Name: 267, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          54.0
sex           0.0
cp            2.0
trestbps    135.0
chol        304.0
fbs           1.0
restecg       1.0
thalach     170.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          2.0
Name: 36, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          58.0
sex           0.0
cp            0.0
trestbps    100.0
chol        248.0
fbs           0.0
restecg       0.0
thalach     122.0
exang         0.0
oldpeak       1.0
slope         1.0
ca            0.0
thal          2.0
Name: 89, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          67.0
sex           1.0
cp            0.0
trestbps    160.0
chol        286.0
fbs           0.0
restecg       0.0
thalach     108.0
exang         1.0
oldpeak       1.5
slope         1.0
ca            3.0
thal          2.0
Name: 165, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          43.0
sex           1.0
cp            0.0
trestbps    150.0
chol        247.0
fbs           0.0
restecg       1.0
thalach     171.0
exang         0.0
oldpeak       1.5
slope         2.0
ca            0.0
thal          2.0
Name: 18, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          66.0
sex           1.0
cp            0.0
trestbps    120.0
chol        302.0
fbs           0.0
restecg       0.0
thalach     151.0
exang         0.0
oldpeak       0.4
slope         1.0
ca            0.0
thal          2.0
Name: 51, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          35.0
sex           1.0
cp            1.0
trestbps    122.0
chol        192.0
fbs           0.0
restecg       1.0
thalach     174.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          2.0
Name: 157, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          54.0
sex           1.0
cp            0.0
trestbps    110.0
chol        206.0
fbs           0.0
restecg       0.0
thalach     108.0
exang         1.0
oldpeak       0.0
slope         1.0
ca            1.0
thal          2.0
Name: 264, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          59.0
sex           1.0
cp            3.0
trestbps    160.0
chol        273.0
fbs           0.0
restecg       0.0
thalach     125.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          2.0
Name: 254, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          62.0
sex           0.0
cp            0.0
trestbps    160.0
chol        164.0
fbs           0.0
restecg       0.0
thalach     145.0
exang         0.0
oldpeak       6.2
slope         0.0
ca            3.0
thal          3.0
Name: 204, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          42.0
sex           1.0
cp            0.0
trestbps    136.0
chol        315.0
fbs           0.0
restecg       1.0
thalach     125.0
exang         1.0
oldpeak       1.8
slope         1.0
ca            0.0
thal          1.0
Name: 280, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          42.0
sex           0.0
cp            2.0
trestbps    120.0
chol        209.0
fbs           0.0
restecg       1.0
thalach     173.0
exang         0.0
oldpeak       0.0
slope         1.0
ca            0.0
thal          2.0
Name: 142, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0

Name: 10, dtype: float64
age          69.0
sex           1.0
cp            3.0
trestbps    160.0
chol        234.0
fbs           1.0
restecg       0.0
thalach     131.0
exang         0.0
oldpeak       0.1
slope         1.0
ca            1.0
thal          2.0
Name: 106, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          59.0
sex           1.0
cp            0.0
trestbps    110.0
chol        239.0
fbs           0.0
restecg       0.0
thalach     142.0
exang         1.0
oldpeak       1.2
slope         1.0
ca            1.0
thal          3.0
Name: 206, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          41.0
sex           1.0
cp            0.0
trestbps    110.0
chol        172.0
fbs           0.0
restecg       0.0
thalach     158.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          3.0
Name: 189, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          43.0
sex           0.0
cp            0.0
trestbps    132.0
chol        341.0
fbs           1.0
restecg       0.0
thalach     136.0
exang         1.0
oldpeak       3.0
slope         1.0
ca            0.0
thal          3.0
Name: 215, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          55.0
sex           1.0
cp            1.0
trestbps    130.0
chol        262.0
fbs           0.0
restecg       1.0
thalach     155.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          2.0
Name: 114, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          52.0
sex           1.0
cp            0.0
trestbps    112.0
chol        230.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            1.0
thal          2.0
Name: 261, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          57.0
sex           1.0
cp            2.0
trestbps    150.0
chol        168.0
fbs           0.0
restecg       1.0
thalach     174.0
exang         0.0
oldpeak       1.6
slope         2.0
ca            0.0
thal          2.0
Name: 9, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          66.0
sex           0.0
cp            0.0
trestbps    178.0
chol        228.0
fbs           1.0
restecg       1.0
thalach     165.0
exang         1.0
oldpeak       1.0
slope         1.0
ca            2.0
thal          3.0
Name: 260, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          68.0
sex           0.0
cp            2.0
trestbps    120.0
chol        211.0
fbs           0.0
restecg       0.0
thalach     115.0
exang         0.0
oldpeak       1.5
slope         1.0
ca            0.0
thal          2.0
Name: 105, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          48.0
sex           1.0
cp            1.0
trestbps    130.0
chol        245.0
fbs           0.0
restecg       0.0
thalach     180.0
exang         0.0
oldpeak       0.2
slope         1.0
ca            0.0
thal          2.0
Name: 41, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          48.0
sex           1.0
cp            2.0
trestbps    124.0
chol        255.0
fbs           1.0
restecg       1.0
thalach     175.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            2.0
thal          2.0
Name: 90, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          59.0
sex           1.0
cp            3.0
trestbps    134.0
chol        204.0
fbs           0.0
restecg       1.0
thalach     162.0
exang         0.0
oldpeak       0.8
slope         2.0
ca            2.0
thal          2.0
Name: 286, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          62.0
sex           1.0
cp            1.0
trestbps    128.0
chol        208.0
fbs           1.0
restecg       0.0
thalach     140.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          2.0
Name: 137, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          55.0
sex           1.0
cp            0.0
trestbps    132.0
chol        353.0
fbs           0.0
restecg       1.0
thalach     132.0
exang         1.0
oldpeak       1.2
slope         1.0
ca            1.0
thal          3.0
Name: 180, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          40.0
sex           1.0
cp            3.0
trestbps    140.0
chol        199.0
fbs           0.0
restecg       1.0
thalach     178.0
exang         1.0
oldpeak       1.4
slope         2.0
ca            0.0
thal          3.0
Name: 24, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          46.0
sex           1.0
cp            2.0
trestbps    150.0
chol        231.0
fbs           0.0
restecg       1.0
thalach     147.0
exang         0.0
oldpeak       3.6
slope         1.0
ca            0.0
thal          2.0
Name: 196, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          47.0
sex           1.0
cp            2.0
trestbps    108.0
chol        243.0
fbs           0.0
restecg       1.0
thalach     152.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          2.0
Name: 230, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          50.0
sex           1.0
cp            0.0
trestbps    144.0
chol        200.0
fbs           0.0
restecg       0.0
thalach     126.0
exang         1.0
oldpeak       0.9
slope         1.0
ca            0.0
thal          3.0
Name: 257, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          51.0
sex           0.0
cp            0.0
trestbps    130.0
chol        305.0
fbs           0.0
restecg       1.0
thalach     142.0
exang         1.0
oldpeak       1.2
slope         1.0
ca            0.0
thal          3.0
Name: 190, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          58.0
sex           1.0
cp            0.0
trestbps    114.0
chol        318.0
fbs           0.0
restecg       2.0
thalach     140.0
exang         0.0
oldpeak       4.4
slope         0.0
ca            3.0
thal          1.0
Name: 291, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          58.0
sex           1.0
cp            0.0
trestbps    100.0
chol        234.0
fbs           0.0
restecg       1.0
thalach     156.0
exang         0.0
oldpeak       0.1
slope         2.0
ca            1.0
thal          3.0
Name: 273, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          46.0
sex           0.0
cp            2.0
trestbps    142.0
chol        177.0
fbs           0.0
restecg       0.0
thalach     160.0
exang         1.0
oldpeak       1.4
slope         0.0
ca            0.0
thal          2.0
Name: 35, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          63.0
sex           1.0
cp            0.0
trestbps    130.0
chol        254.0
fbs           0.0
restecg       0.0
thalach     147.0
exang         0.0
oldpeak       1.4
slope         1.0
ca            1.0
thal          3.0
Name: 168, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          57.0
sex           0.0
cp            1.0
trestbps    130.0
chol        236.0
fbs           0.0
restecg       0.0
thalach     174.0
exang         0.0
oldpeak       0.0
slope         1.0
ca            1.0
thal          2.0
Name: 302, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          48.0
sex           1.0
cp            0.0
trestbps    124.0
chol        274.0
fbs           0.0
restecg       0.0
thalach     166.0
exang         0.0
oldpeak       0.5
slope         1.0
ca            0.0
thal          3.0
Name: 245, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          62.0
sex           1.0
cp            1.0
trestbps    120.0
chol        281.0
fbs           0.0
restecg       0.0
thalach     103.0
exang         0.0
oldpeak       1.4
slope         1.0
ca            1.0
thal          3.0
Name: 226, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          43.0
sex           1.0
cp            0.0
trestbps    132.0
chol        247.0
fbs           1.0
restecg       0.0
thalach     143.0
exang         1.0
oldpeak       0.1
slope         1.0
ca            4.0
thal          3.0
Name: 251, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          43.0
sex           1.0
cp            0.0
trestbps    110.0
chol        211.0
fbs           0.0
restecg       1.0
thalach     161.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          3.0

Name: 113, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          51.0
sex           1.0
cp            2.0
trestbps    125.0
chol        245.0
fbs           1.0
restecg       0.0
thalach     166.0
exang         0.0
oldpeak       2.4
slope         1.0
ca            0.0
thal          2.0
Name: 76, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          34.0
sex           1.0
cp            3.0
trestbps    118.0
chol        182.0
fbs           0.0
restecg       0.0
thalach     174.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          2.0
Name: 58, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          50.0
sex           1.0
cp            2.0
trestbps    140.0
chol        233.0
fbs           0.0
restecg       1.0
thalach     163.0
exang         0.0
oldpeak       0.6
slope         1.0
ca            1.0
thal          3.0
Name: 188, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          51.0
sex           1.0
cp            0.0
trestbps    140.0
chol        299.0
fbs           0.0
restecg       1.0
thalach     173.0
exang         1.0
oldpeak       1.6
slope         2.0
ca            0.0
thal          3.0
Name: 235, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          64.0
sex           1.0
cp            0.0
trestbps    120.0
chol        246.0
fbs           0.0
restecg       0.0
thalach      96.0
exang         1.0
oldpeak       2.2
slope         0.0
ca            1.0
thal          2.0
Name: 233, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          64.0
sex           1.0
cp            0.0
trestbps    128.0
chol        263.0
fbs           0.0
restecg       1.0
thalach     105.0
exang         1.0
oldpeak       0.2
slope         1.0
ca            1.0
thal          3.0
Name: 139, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          58.0
sex           1.0
cp            0.0
trestbps    128.0
chol        259.0
fbs           0.0
restecg       0.0
thalach     130.0
exang         1.0
oldpeak       3.0
slope         1.0
ca            2.0
thal          3.0
Name: 256, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          42.0
sex           1.0
cp            1.0
trestbps    120.0
chol        295.0
fbs           0.0
restecg       1.0
thalach     162.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          2.0
Name: 132, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          61.0
sex           1.0
cp            0.0
trestbps    148.0
chol        203.0
fbs           0.0
restecg       1.0
thalach     161.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            1.0
thal          3.0
Name: 290, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          50.0
sex           1.0
cp            0.0
trestbps    150.0
chol        243.0
fbs           0.0
restecg       0.0
thalach     128.0
exang         0.0
oldpeak       2.6
slope         1.0
ca            0.0
thal          3.0
Name: 184, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          54.0
sex           0.0
cp            2.0
trestbps    160.0
chol        201.0
fbs           0.0
restecg       1.0
thalach     163.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            1.0
thal          2.0
Name: 130, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          43.0
sex           1.0
cp            0.0
trestbps    120.0
chol        177.0
fbs           0.0
restecg       0.0
thalach     120.0
exang         1.0
oldpeak       2.5
slope         1.0
ca            0.0
thal          3.0
Name: 178, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          63.0
sex           0.0
cp            1.0
trestbps    140.0
chol        195.0
fbs           0.0
restecg       1.0
thalach     179.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            2.0
thal          2.0
Name: 102, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          44.0
sex           1.0
cp            2.0
trestbps    130.0
chol        233.0
fbs           0.0
restecg       1.0
thalach     179.0
exang         1.0
oldpeak       0.4
slope         2.0
ca            0.0
thal          2.0
Name: 21, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          47.0
sex           1.0
cp            2.0
trestbps    130.0
chol        253.0
fbs           0.0
restecg       1.0
thalach     179.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          2.0
Name: 156, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          54.0
sex           1.0
cp            0.0
trestbps    120.0
chol        188.0
fbs           0.0
restecg       1.0
thalach     113.0
exang         0.0
oldpeak       1.4
slope         1.0
ca            1.0
thal          3.0
Name: 192, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          60.0
sex           1.0
cp            0.0
trestbps    130.0
chol        206.0
fbs           0.0
restecg       0.0
thalach     132.0
exang         1.0
oldpeak       2.4
slope         1.0
ca            2.0
thal          3.0
Name: 174, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          55.0
sex           0.0
cp            0.0
trestbps    180.0
chol        327.0
fbs           0.0
restecg       2.0
thalach     117.0
exang         1.0
oldpeak       3.4
slope         1.0
ca            0.0
thal          2.0
Name: 266, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          59.0
sex           1.0
cp            2.0
trestbps    150.0
chol        212.0
fbs           1.0
restecg       1.0
thalach     157.0
exang         0.0
oldpeak       1.6
slope         2.0
ca            0.0
thal          2.0
Name: 26, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          41.0
sex           1.0
cp            2.0
trestbps    112.0
chol        250.0
fbs           0.0
restecg       1.0
thalach     179.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          2.0
Name: 80, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          64.0
sex           1.0
cp            0.0
trestbps    145.0
chol        212.0
fbs           0.0
restecg       0.0
thalach     132.0
exang         0.0
oldpeak       2.0
slope         1.0
ca            2.0
thal          1.0
Name: 242, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          65.0
sex           1.0
cp            3.0
trestbps    138.0
chol        282.0
fbs           1.0
restecg       0.0
thalach     174.0
exang         0.0
oldpeak       1.4
slope         1.0
ca            1.0
thal          2.0
Name: 222, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          65.0
sex           0.0
cp            2.0
trestbps    155.0
chol        269.0
fbs           0.0
restecg       1.0
thalach     148.0
exang         0.0
oldpeak       0.8
slope         2.0
ca            0.0
thal          2.0
Name: 38, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          41.0
sex           0.0
cp            2.0
trestbps    112.0
chol        268.0
fbs           0.0
restecg       0.0
thalach     172.0
exang         1.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          2.0
Name: 122, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          58.0
sex           1.0
cp            0.0
trestbps    125.0
chol        300.0
fbs           0.0
restecg       0.0
thalach     171.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            2.0
thal          3.0
Name: 236, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          57.0
sex           1.0
cp            2.0
trestbps    128.0
chol        229.0
fbs           0.0
restecg       0.0
thalach     150.0
exang         0.0
oldpeak       0.4
slope         1.0
ca            1.0
thal          3.0
Name: 210, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          59.0
sex           1.0
cp            0.0
trestbps    135.0
chol        234.0
fbs           0.0
restecg       1.0
thalach     161.0
exang         0.0
oldpeak       0.5
slope         1.0
ca            0.0
thal          3.0
Name: 20, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          58.0
sex           1.0
cp            0.0
trestbps    146.0
chol        218.0
fbs           0.0
restecg       1.0
thalach     105.0
exang         0.0
oldpeak       2.0
slope         1.0
ca            1.0
thal          3.0
Name: 276, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          49.0
sex           1.0
cp            1.0
trestbps    130.0
chol        266.0
fbs           0.0
restecg       1.0
thalach     171.0
exang         0.0
oldpeak       0.6
slope         2.0
ca            0.0
thal          2.0

Name: 12, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          52.0
sex           1.0
cp            0.0
trestbps    128.0
chol        255.0
fbs           0.0
restecg       1.0
thalach     161.0
exang         1.0
oldpeak       0.0
slope         2.0
ca            1.0
thal          3.0
Name: 205, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          70.0
sex           1.0
cp            0.0
trestbps    145.0
chol        174.0
fbs           0.0
restecg       1.0
thalach     125.0
exang         1.0
oldpeak       2.6
slope         0.0
ca            0.0
thal          3.0
Name: 225, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          53.0
sex           0.0
cp            0.0
trestbps    138.0
chol        234.0
fbs           0.0
restecg       0.0
thalach     160.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          2.0
Name: 49, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          54.0
sex           1.0
cp            2.0
trestbps    150.0
chol        232.0
fbs           0.0
restecg       0.0
thalach     165.0
exang         0.0
oldpeak       1.6
slope         2.0
ca            0.0
thal          3.0
Name: 37, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          69.0
sex           0.0
cp            3.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     151.0
exang         0.0
oldpeak       1.8
slope         2.0
ca            2.0
thal          2.0
Name: 19, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          54.0
sex           1.0
cp            0.0
trestbps    122.0
chol        286.0
fbs           0.0
restecg       0.0
thalach     116.0
exang         1.0
oldpeak       3.2
slope         1.0
ca            2.0
thal          2.0
Name: 268, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          60.0
sex           1.0
cp            0.0
trestbps    130.0
chol        253.0
fbs           0.0
restecg       1.0
thalach     144.0
exang         1.0
oldpeak       1.4
slope         2.0
ca            1.0
thal          3.0
Name: 186, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          40.0
sex           1.0
cp            0.0
trestbps    152.0
chol        223.0
fbs           0.0
restecg       1.0
thalach     181.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          3.0
Name: 283, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          67.0
sex           1.0
cp            2.0
trestbps    152.0
chol        212.0
fbs           0.0
restecg       0.0
thalach     150.0
exang         0.0
oldpeak       0.8
slope         1.0
ca            0.0
thal          3.0
Name: 293, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          60.0
sex           0.0
cp            3.0
trestbps    150.0
chol        240.0
fbs           0.0
restecg       1.0
thalach     171.0
exang         0.0
oldpeak       0.9
slope         2.0
ca            0.0
thal          2.0
Name: 147, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          62.0
sex           0.0
cp            0.0
trestbps    150.0
chol        244.0
fbs           0.0
restecg       1.0
thalach     154.0
exang         1.0
oldpeak       1.4
slope         1.0
ca            0.0
thal          2.0
Name: 258, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          51.0
sex           1.0
cp            3.0
trestbps    125.0
chol        213.0
fbs           0.0
restecg       0.0
thalach     125.0
exang         1.0
oldpeak       1.4
slope         2.0
ca            1.0
thal          2.0
Name: 34, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          29.0
sex           1.0
cp            1.0
trestbps    130.0
chol        204.0
fbs           0.0
restecg       0.0
thalach     202.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          2.0
Name: 72, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          53.0
sex           1.0
cp            2.0
trestbps    130.0
chol        197.0
fbs           1.0
restecg       0.0
thalach     152.0
exang         0.0
oldpeak       1.2
slope         0.0
ca            0.0
thal          2.0
Name: 29, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          65.0
sex           0.0
cp            0.0
trestbps    150.0
chol        225.0
fbs           0.0
restecg       0.0
thalach     114.0
exang         0.0
oldpeak       1.0
slope         1.0
ca            3.0
thal          3.0
Name: 181, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          57.0
sex           1.0
cp            0.0
trestbps    110.0
chol        201.0
fbs           0.0
restecg       1.0
thalach     126.0
exang         1.0
oldpeak       1.5
slope         1.0
ca            0.0
thal          1.0
Name: 138, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          56.0
sex           1.0
cp            0.0
trestbps    130.0
chol        283.0
fbs           1.0
restecg       0.0
thalach     103.0
exang         1.0
oldpeak       1.6
slope         0.0
ca            0.0
thal          3.0
Name: 269, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          47.0
sex           1.0
cp            0.0
trestbps    112.0
chol        204.0
fbs           0.0
restecg       1.0
thalach     143.0
exang         0.0
oldpeak       0.1
slope         2.0
ca            0.0
thal          2.0
Name: 126, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          45.0
sex           0.0
cp            1.0
trestbps    130.0
chol        234.0
fbs           0.0
restecg       0.0
thalach     175.0
exang         0.0
oldpeak       0.6
slope         1.0
ca            0.0
thal          2.0
Name: 67, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          59.0
sex           1.0
cp            3.0
trestbps    178.0
chol        270.0
fbs           0.0
restecg       0.0
thalach     145.0
exang         0.0
oldpeak       4.2
slope         0.0
ca            0.0
thal          3.0
Name: 101, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          63.0
sex           0.0
cp            0.0
trestbps    150.0
chol        407.0
fbs           0.0
restecg       0.0
thalach     154.0
exang         0.0
oldpeak       4.0
slope         1.0
ca            3.0
thal          3.0
Name: 220, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          35.0
sex           1.0
cp            0.0
trestbps    120.0
chol        198.0
fbs           0.0
restecg       1.0
thalach     130.0
exang         1.0
oldpeak       1.6
slope         1.0
ca            0.0
thal          3.0
Name: 227, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          42.0
sex           1.0
cp            2.0
trestbps    120.0
chol        240.0
fbs           1.0
restecg       1.0
thalach     194.0
exang         0.0
oldpeak       0.8
slope         0.0
ca            0.0
thal          3.0
Name: 103, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          48.0
sex           1.0
cp            1.0
trestbps    110.0
chol        229.0
fbs           0.0
restecg       1.0
thalach     168.0
exang         0.0
oldpeak       1.0
slope         0.0
ca            0.0
thal          3.0
Name: 171, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          52.0
sex           1.0
cp            0.0
trestbps    128.0
chol        204.0
fbs           1.0
restecg       1.0
thalach     156.0
exang         1.0
oldpeak       1.0
slope         1.0
ca            0.0
thal          0.0
Name: 281, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          42.0
sex           1.0
cp            2.0
trestbps    130.0
chol        180.0
fbs           0.0
restecg       1.0
thalach     150.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          2.0
Name: 149, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          57.0
sex           1.0
cp            0.0
trestbps    110.0
chol        335.0
fbs           0.0
restecg       1.0
thalach     143.0
exang         1.0
oldpeak       3.0
slope         1.0
ca            1.0
thal          3.0
Name: 288, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0

Name: 10, dtype: float64
age          53.0
sex           0.0
cp            2.0
trestbps    128.0
chol        216.0
fbs           0.0
restecg       0.0
thalach     115.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          0.0
Name: 48, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          42.0
sex           1.0
cp            3.0
trestbps    148.0
chol        244.0
fbs           0.0
restecg       0.0
thalach     178.0
exang         0.0
oldpeak       0.8
slope         2.0
ca            2.0
thal          2.0
Name: 100, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          66.0
sex           1.0
cp            0.0
trestbps    160.0
chol        228.0
fbs           0.0
restecg       0.0
thalach     138.0
exang         0.0
oldpeak       2.3
slope         2.0
ca            0.0
thal          1.0
Name: 150, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          58.0
sex           0.0
cp            2.0
trestbps    120.0
chol        340.0
fbs           0.0
restecg       1.0
thalach     172.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          2.0
Name: 16, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          58.0
sex           1.0
cp            2.0
trestbps    105.0
chol        240.0
fbs           0.0
restecg       0.0
thalach     154.0
exang         1.0
oldpeak       0.6
slope         1.0
ca            0.0
thal          3.0
Name: 79, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          63.0
sex           1.0
cp            0.0
trestbps    130.0
chol        330.0
fbs           1.0
restecg       0.0
thalach     132.0
exang         1.0
oldpeak       1.8
slope         2.0
ca            3.0
thal          3.0
Name: 217, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          53.0
sex           1.0
cp            2.0
trestbps    130.0
chol        246.0
fbs           1.0
restecg       0.0
thalach     173.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            3.0
thal          2.0
Name: 99, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          39.0
sex           0.0
cp            2.0
trestbps    138.0
chol        220.0
fbs           0.0
restecg       1.0
thalach     152.0
exang         0.0
oldpeak       0.0
slope         1.0
ca            0.0
thal          2.0
Name: 154, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          60.0
sex           1.0
cp            0.0
trestbps    140.0
chol        293.0
fbs           0.0
restecg       0.0
thalach     170.0
exang         0.0
oldpeak       1.2
slope         1.0
ca            2.0
thal          3.0
Name: 237, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          48.0
sex           1.0
cp            0.0
trestbps    122.0
chol        222.0
fbs           0.0
restecg       0.0
thalach     186.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          2.0
Name: 56, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          62.0
sex           1.0
cp            0.0
trestbps    120.0
chol        267.0
fbs           0.0
restecg       1.0
thalach      99.0
exang         1.0
oldpeak       1.8
slope         1.0
ca            2.0
thal          3.0
Name: 198, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          62.0
sex           1.0
cp            2.0
trestbps    130.0
chol        231.0
fbs           0.0
restecg       1.0
thalach     146.0
exang         0.0
oldpeak       1.8
slope         1.0
ca            3.0
thal          3.0
Name: 52, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          44.0
sex           0.0
cp            2.0
trestbps    108.0
chol        141.0
fbs           0.0
restecg       1.0
thalach     175.0
exang         0.0
oldpeak       0.6
slope         1.0
ca            0.0
thal          2.0
Name: 53, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          71.0
sex           0.0
cp            1.0
trestbps    160.0
chol        302.0
fbs           0.0
restecg       1.0
thalach     162.0
exang         0.0
oldpeak       0.4
slope         2.0
ca            2.0
thal          2.0
Name: 25, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          64.0
sex           0.0
cp            2.0
trestbps    140.0
chol        313.0
fbs           0.0
restecg       1.0
thalach     133.0
exang         0.0
oldpeak       0.2
slope         2.0
ca            0.0
thal          3.0
Name: 112, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          67.0
sex           0.0
cp            2.0
trestbps    152.0
chol        277.0
fbs           0.0
restecg       1.0
thalach     172.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            1.0
thal          2.0
Name: 127, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          70.0
sex           1.0
cp            1.0
trestbps    156.0
chol        245.0
fbs           0.0
restecg       0.0
thalach     143.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          2.0
Name: 145, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          59.0
sex           1.0
cp            0.0
trestbps    138.0
chol        271.0
fbs           0.0
restecg       0.0
thalach     182.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          2.0
Name: 121, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          45.0
sex           1.0
cp            3.0
trestbps    110.0
chol        264.0
fbs           0.0
restecg       1.0
thalach     132.0
exang         0.0
oldpeak       1.2
slope         1.0
ca            0.0
thal          3.0
Name: 299, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          53.0
sex           1.0
cp            0.0
trestbps    123.0
chol        282.0
fbs           0.0
restecg       1.0
thalach      95.0
exang         1.0
oldpeak       2.0
slope         1.0
ca            2.0
thal          3.0
Name: 262, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          51.0
sex           1.0
cp            0.0
trestbps    140.0
chol        298.0
fbs           0.0
restecg       1.0
thalach     122.0
exang         1.0
oldpeak       4.2
slope         1.0
ca            3.0
thal          3.0
Name: 250, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          68.0
sex           1.0
cp            0.0
trestbps    144.0
chol        193.0
fbs           1.0
restecg       1.0
thalach     141.0
exang         0.0
oldpeak       3.4
slope         1.0
ca            2.0
thal          3.0
Name: 300, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          71.0
sex           0.0
cp            0.0
trestbps    112.0
chol        149.0
fbs           0.0
restecg       1.0
thalach     125.0
exang         0.0
oldpeak       1.6
slope         1.0
ca            0.0
thal          2.0
Name: 151, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          65.0
sex           1.0
cp            0.0
trestbps    135.0
chol        254.0
fbs           0.0
restecg       0.0
thalach     127.0
exang         0.0
oldpeak       2.8
slope         1.0
ca            1.0
thal          3.0
Name: 218, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          59.0
sex           1.0
cp            0.0
trestbps    164.0
chol        176.0
fbs           1.0
restecg       0.0
thalach      90.0
exang         0.0
oldpeak       1.0
slope         1.0
ca            2.0
thal          1.0
Name: 297, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          38.0
sex           1.0
cp            2.0
trestbps    138.0
chol        175.0
fbs           0.0
restecg       1.0
thalach     173.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            4.0
thal          2.0
Name: 164, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          55.0
sex           0.0
cp            1.0
trestbps    132.0
chol        342.0
fbs           0.0
restecg       1.0
thalach     166.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 161, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          56.0
sex           1.0
cp            1.0
trestbps    130.0
chol        221.0
fbs           0.0
restecg       0.0
thalach     163.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          3.0
Name: 159, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          52.0
sex           1.0
cp            0.0
trestbps    108.0
chol        233.0
fbs           1.0
restecg       1.0
thalach     147.0
exang         0.0
oldpeak       0.1
slope         2.0
ca            3.0
thal          3.0
Name: 97, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          56.0
sex           0.0
cp            1.0
trestbps    140.0
chol        294.0
fbs           0.0
restecg       0.0
thalach     153.0
exang         0.0
oldpeak       1.3
slope         1.0
ca            0.0
thal          2.0
Name: 6, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          52.0
sex           1.0
cp            1.0
trestbps    128.0
chol        205.0
fbs           1.0
restecg       1.0
thalach     184.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          2.0
Name: 78, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          60.0
sex           0.0
cp            2.0
trestbps    102.0
chol        318.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            1.0
thal          2.0
Name: 82, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          70.0
sex           1.0
cp            2.0
trestbps    160.0
chol        269.0
fbs           0.0
restecg       1.0
thalach     112.0
exang         1.0
oldpeak       2.9
slope         1.0
ca            1.0
thal          3.0

Name: 240, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          61.0
sex           1.0
cp            3.0
trestbps    134.0
chol        234.0
fbs           0.0
restecg       1.0
thalach     145.0
exang         0.0
oldpeak       2.6
slope         1.0
ca            2.0
thal          2.0
Name: 271, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          56.0
sex           1.0
cp            1.0
trestbps    120.0
chol        240.0
fbs           0.0
restecg       1.0
thalach     169.0
exang         0.0
oldpeak       0.0
slope         0.0
ca            0.0
thal          2.0
Name: 160, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          61.0
sex           1.0
cp            0.0
trestbps    140.0
chol        207.0
fbs           0.0
restecg       0.0
thalach     138.0
exang         1.0
oldpeak       1.9
slope         2.0
ca            1.0
thal          3.0
Name: 284, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          43.0
sex           1.0
cp            2.0
trestbps    130.0
chol        315.0
fbs           0.0
restecg       1.0
thalach     162.0
exang         0.0
oldpeak       1.9
slope         2.0
ca            1.0
thal          2.0
Name: 98, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          58.0
sex           1.0
cp            2.0
trestbps    140.0
chol        211.0
fbs           1.0
restecg       0.0
thalach     165.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          2.0
Name: 64, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          45.0
sex           1.0
cp            0.0
trestbps    104.0
chol        208.0
fbs           0.0
restecg       0.0
thalach     148.0
exang         1.0
oldpeak       3.0
slope         1.0
ca            0.0
thal          2.0
Name: 42, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          49.0
sex           0.0
cp            1.0
trestbps    134.0
chol        271.0
fbs           0.0
restecg       1.0
thalach     162.0
exang         0.0
oldpeak       0.0
slope         1.0
ca            0.0
thal          2.0
Name: 131, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          42.0
sex           1.0
cp            0.0
trestbps    140.0
chol        226.0
fbs           0.0
restecg       1.0
thalach     178.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          2.0
Name: 22, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          43.0
sex           1.0
cp            0.0
trestbps    115.0
chol        303.0
fbs           0.0
restecg       1.0
thalach     181.0
exang         0.0
oldpeak       1.2
slope         1.0
ca            0.0
thal          2.0
Name: 141, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          54.0
sex           1.0
cp            0.0
trestbps    124.0
chol        266.0
fbs           0.0
restecg       0.0
thalach     109.0
exang         1.0
oldpeak       2.2
slope         1.0
ca            1.0
thal          3.0
Name: 187, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          56.0
sex           1.0
cp            2.0
trestbps    130.0
chol        256.0
fbs           1.0
restecg       0.0
thalach     142.0
exang         1.0
oldpeak       0.6
slope         1.0
ca            1.0
thal          1.0
Name: 170, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          69.0
sex           1.0
cp            2.0
trestbps    140.0
chol        254.0
fbs           0.0
restecg       0.0
thalach     146.0
exang         0.0
oldpeak       2.0
slope         1.0
ca            3.0
thal          3.0
Name: 249, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          60.0
sex           0.0
cp            0.0
trestbps    150.0
chol        258.0
fbs           0.0
restecg       0.0
thalach     157.0
exang         0.0
oldpeak       2.6
slope         1.0
ca            2.0
thal          3.0
Name: 207, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          52.0
sex           1.0
cp            3.0
trestbps    152.0
chol        298.0
fbs           1.0
restecg       1.0
thalach     178.0
exang         0.0
oldpeak       1.2
slope         1.0
ca            0.0
thal          3.0
Name: 83, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          59.0
sex           1.0
cp            1.0
trestbps    140.0
chol        221.0
fbs           0.0
restecg       1.0
thalach     164.0
exang         1.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          2.0
Name: 77, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          51.0
sex           1.0
cp            2.0
trestbps    110.0
chol        175.0
fbs           0.0
restecg       1.0
thalach     123.0
exang         0.0
oldpeak       0.6
slope         2.0
ca            0.0
thal          2.0
Name: 27, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          45.0
sex           1.0
cp            1.0
trestbps    128.0
chol        308.0
fbs           0.0
restecg       0.0
thalach     170.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          2.0
Name: 81, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          62.0
sex           0.0
cp            0.0
trestbps    140.0
chol        394.0
fbs           0.0
restecg       0.0
thalach     157.0
exang         0.0
oldpeak       1.2
slope         1.0
ca            0.0
thal          2.0
Name: 96, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          55.0
sex           1.0
cp            0.0
trestbps    140.0
chol        217.0
fbs           0.0
restecg       1.0
thalach     111.0
exang         1.0
oldpeak       5.6
slope         0.0
ca            0.0
thal          3.0
Name: 221, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          68.0
sex           1.0
cp            2.0
trestbps    180.0
chol        274.0
fbs           1.0
restecg       0.0
thalach     150.0
exang         1.0
oldpeak       1.6
slope         1.0
ca            0.0
thal          3.0
Name: 203, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          41.0
sex           1.0
cp            2.0
trestbps    130.0
chol        214.0
fbs           0.0
restecg       0.0
thalach     168.0
exang         0.0
oldpeak       2.0
slope         1.0
ca            0.0
thal          2.0
Name: 116, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          44.0
sex           1.0
cp            0.0
trestbps    120.0
chol        169.0
fbs           0.0
restecg       1.0
thalach     144.0
exang         1.0
oldpeak       2.8
slope         0.0
ca            0.0
thal          1.0
Name: 294, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          65.0
sex           0.0
cp            2.0
trestbps    140.0
chol        417.0
fbs           1.0
restecg       0.0
thalach     157.0
exang         0.0
oldpeak       0.8
slope         2.0
ca            1.0
thal          2.0
Name: 28, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          48.0
sex           1.0
cp            0.0
trestbps    130.0
chol        256.0
fbs           1.0
restecg       0.0
thalach     150.0
exang         1.0
oldpeak       0.0
slope         2.0
ca            2.0
thal          3.0
Name: 219, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          56.0
sex           1.0
cp            3.0
trestbps    120.0
chol        193.0
fbs           0.0
restecg       0.0
thalach     162.0
exang         0.0
oldpeak       1.9
slope         1.0
ca            0.0
thal          3.0
Name: 117, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          58.0
sex           0.0
cp            0.0
trestbps    170.0
chol        225.0
fbs           1.0
restecg       0.0
thalach     146.0
exang         1.0
oldpeak       2.8
slope         1.0
ca            2.0
thal          1.0
Name: 292, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          58.0
sex           1.0
cp            1.0
trestbps    120.0
chol        284.0
fbs           0.0
restecg       0.0
thalach     160.0
exang         0.0
oldpeak       1.8
slope         1.0
ca            0.0
thal          2.0
Name: 172, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          60.0
sex           1.0
cp            0.0
trestbps    125.0
chol        258.0
fbs           0.0
restecg       0.0
thalach     141.0
exang         1.0
oldpeak       2.8
slope         1.0
ca            1.0
thal          3.0

Name: 201, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          58.0
sex           0.0
cp            3.0
trestbps    150.0
chol        283.0
fbs           1.0
restecg       0.0
thalach     162.0
exang         0.0
oldpeak       1.0
slope         2.0
ca            0.0
thal          2.0
Name: 14, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          56.0
sex           1.0
cp            1.0
trestbps    120.0
chol        236.0
fbs           0.0
restecg       1.0
thalach     178.0
exang         0.0
oldpeak       0.8
slope         2.0
ca            0.0
thal          2.0
Name: 3, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          57.0
sex           0.0
cp            0.0
trestbps    140.0
chol        241.0
fbs           0.0
restecg       1.0
thalach     123.0
exang         1.0
oldpeak       0.2
slope         1.0
ca            0.0
thal          3.0
Name: 298, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          64.0
sex           1.0
cp            3.0
trestbps    110.0
chol        211.0
fbs           0.0
restecg       0.0
thalach     144.0
exang         1.0
oldpeak       1.8
slope         1.0
ca            0.0
thal          2.0
Name: 13, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          54.0
sex           1.0
cp            2.0
trestbps    125.0
chol        273.0
fbs           0.0
restecg       0.0
thalach     152.0
exang         0.0
oldpeak       0.5
slope         0.0
ca            1.0
thal          2.0
Name: 33, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          59.0
sex           1.0
cp            2.0
trestbps    126.0
chol        218.0
fbs           1.0
restecg       1.0
thalach     134.0
exang         0.0
oldpeak       2.2
slope         1.0
ca            1.0
thal          1.0
Name: 282, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          59.0
sex           0.0
cp            0.0
trestbps    174.0
chol        249.0
fbs           0.0
restecg       1.0
thalach     143.0
exang         1.0
oldpeak       0.0
slope         1.0
ca            0.0
thal          2.0
Name: 241, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          53.0
sex           1.0
cp            0.0
trestbps    140.0
chol        203.0
fbs           1.0
restecg       0.0
thalach     155.0
exang         1.0
oldpeak       3.1
slope         0.0
ca            0.0
thal          3.0
Name: 169, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          71.0
sex           0.0
cp            2.0
trestbps    110.0
chol        265.0
fbs           1.0
restecg       0.0
thalach     130.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            1.0
thal          2.0
Name: 60, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          56.0
sex           1.0
cp            0.0
trestbps    125.0
chol        249.0
fbs           1.0
restecg       0.0
thalach     144.0
exang         1.0
oldpeak       1.2
slope         1.0
ca            1.0
thal          2.0
Name: 214, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          50.0
sex           1.0
cp            2.0
trestbps    129.0
chol        196.0
fbs           0.0
restecg       1.0
thalach     163.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          2.0
Name: 104, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          41.0
sex           1.0
cp            1.0
trestbps    120.0
chol        157.0
fbs           0.0
restecg       1.0
thalach     182.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          2.0
Name: 162, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          74.0
sex           0.0
cp            1.0
trestbps    120.0
chol        269.0
fbs           0.0
restecg       0.0
thalach     121.0
exang         1.0
oldpeak       0.2
slope         2.0
ca            1.0
thal          2.0
Name: 129, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          54.0
sex           0.0
cp            2.0
trestbps    110.0
chol        214.0
fbs           0.0
restecg       1.0
thalach     158.0
exang         0.0
oldpeak       1.6
slope         1.0
ca            0.0
thal          2.0
Name: 88, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          58.0
sex           1.0
cp            2.0
trestbps    112.0
chol        230.0
fbs           0.0
restecg       0.0
thalach     165.0
exang         0.0
oldpeak       2.5
slope         1.0
ca            1.0
thal          3.0
Name: 183, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          68.0
sex           1.0
cp            2.0
trestbps    118.0
chol        277.0
fbs           0.0
restecg       1.0
thalach     151.0
exang         0.0
oldpeak       1.0
slope         2.0
ca            1.0
thal          3.0
Name: 86, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          66.0
sex           0.0
cp            2.0
trestbps    146.0
chol        278.0
fbs           0.0
restecg       0.0
thalach     152.0
exang         0.0
oldpeak       0.0
slope         1.0
ca            1.0
thal          2.0
Name: 153, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          55.0
sex           0.0
cp            1.0
trestbps    135.0
chol        250.0
fbs           0.0
restecg       0.0
thalach     161.0
exang         0.0
oldpeak       1.4
slope         1.0
ca            0.0
thal          2.0
Name: 75, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          61.0
sex           0.0
cp            0.0
trestbps    130.0
chol        330.0
fbs           0.0
restecg       0.0
thalach     169.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          2.0
Name: 182, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          45.0
sex           0.0
cp            1.0
trestbps    112.0
chol        160.0
fbs           0.0
restecg       1.0
thalach     138.0
exang         0.0
oldpeak       0.0
slope         1.0
ca            0.0
thal          2.0
Name: 94, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          57.0
sex           0.0
cp            0.0
trestbps    120.0
chol        354.0
fbs           0.0
restecg       1.0
thalach     163.0
exang         1.0
oldpeak       0.6
slope         2.0
ca            0.0
thal          2.0
Name: 4, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          66.0
sex           1.0
cp            1.0
trestbps    160.0
chol        246.0
fbs           0.0
restecg       1.0
thalach     120.0
exang         1.0
oldpeak       0.0
slope         1.0
ca            3.0
thal          1.0
Name: 247, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          50.0
sex           0.0
cp            0.0
trestbps    110.0
chol        254.0
fbs           0.0
restecg       0.0
thalach     159.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          2.0
Name: 109, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          64.0
sex           0.0
cp            0.0
trestbps    180.0
chol        325.0
fbs           0.0
restecg       1.0
thalach     154.0
exang         1.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          2.0
Name: 110, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          64.0
sex           1.0
cp            2.0
trestbps    125.0
chol        309.0
fbs           0.0
restecg       1.0
thalach     131.0
exang         1.0
oldpeak       1.8
slope         1.0
ca            0.0
thal          3.0
Name: 229, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          67.0
sex           0.0
cp            2.0
trestbps    115.0
chol        564.0
fbs           0.0
restecg       0.0
thalach     160.0
exang         0.0
oldpeak       1.6
slope         1.0
ca            0.0
thal          3.0
Name: 85, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          44.0
sex           1.0
cp            2.0
trestbps    120.0
chol        226.0
fbs           0.0
restecg       1.0
thalach     169.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          2.0
Name: 148, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          47.0
sex           1.0
cp            2.0
trestbps    138.0
chol        257.0
fbs           0.0
restecg       0.0
thalach     156.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          2.0
Name: 47, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          67.0
sex           1.0
cp            0.0
trestbps    125.0
chol        254.0
fbs           1.0
restecg       1.0
thalach     163.0
exang         0.0
oldpeak       0.2
slope         1.0
ca            2.0
thal          3.0

Name: 197, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          58.0
sex           1.0
cp            0.0
trestbps    128.0
chol        216.0
fbs           0.0
restecg       0.0
thalach     131.0
exang         1.0
oldpeak       2.2
slope         1.0
ca            3.0
thal          3.0
Name: 191, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          41.0
sex           1.0
cp            1.0
trestbps    135.0
chol        203.0
fbs           0.0
restecg       1.0
thalach     132.0
exang         0.0
oldpeak       0.0
slope         1.0
ca            0.0
thal          1.0
Name: 63, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          52.0
sex           1.0
cp            1.0
trestbps    120.0
chol        325.0
fbs           0.0
restecg       1.0
thalach     172.0
exang         0.0
oldpeak       0.2
slope         2.0
ca            0.0
thal          2.0
Name: 45, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          67.0
sex           0.0
cp            0.0
trestbps    106.0
chol        223.0
fbs           0.0
restecg       1.0
thalach     142.0
exang         0.0
oldpeak       0.3
slope         2.0
ca            2.0
thal          2.0
Name: 143, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          61.0
sex           1.0
cp            0.0
trestbps    138.0
chol        166.0
fbs           0.0
restecg       0.0
thalach     125.0
exang         1.0
oldpeak       3.6
slope         1.0
ca            1.0
thal          2.0
Name: 279, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          62.0
sex           0.0
cp            0.0
trestbps    140.0
chol        268.0
fbs           0.0
restecg       0.0
thalach     160.0
exang         0.0
oldpeak       3.6
slope         0.0
ca            2.0
thal          2.0
Name: 167, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          54.0
sex           0.0
cp            2.0
trestbps    108.0
chol        267.0
fbs           0.0
restecg       0.0
thalach     167.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          2.0
Name: 123, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          64.0
sex           1.0
cp            2.0
trestbps    140.0
chol        335.0
fbs           0.0
restecg       1.0
thalach     158.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          2.0
Name: 177, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          46.0
sex           1.0
cp            0.0
trestbps    140.0
chol        311.0
fbs           0.0
restecg       1.0
thalach     120.0
exang         1.0
oldpeak       1.8
slope         1.0
ca            2.0
thal          3.0
Name: 285, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          44.0
sex           1.0
cp            2.0
trestbps    140.0
chol        235.0
fbs           0.0
restecg       0.0
thalach     180.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          2.0
Name: 46, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          50.0
sex           0.0
cp            1.0
trestbps    120.0
chol        244.0
fbs           0.0
restecg       1.0
thalach     162.0
exang         0.0
oldpeak       1.1
slope         2.0
ca            0.0
thal          2.0
Name: 108, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          52.0
sex           1.0
cp            3.0
trestbps    118.0
chol        186.0
fbs           0.0
restecg       0.0
thalach     190.0
exang         0.0
oldpeak       0.0
slope         1.0
ca            0.0
thal          1.0
Name: 62, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          58.0
sex           1.0
cp            2.0
trestbps    132.0
chol        224.0
fbs           0.0
restecg       0.0
thalach     173.0
exang         0.0
oldpeak       3.2
slope         2.0
ca            2.0
thal          3.0
Name: 173, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          45.0
sex           0.0
cp            0.0
trestbps    138.0
chol        236.0
fbs           0.0
restecg       0.0
thalach     152.0
exang         1.0
oldpeak       0.2
slope         1.0
ca            0.0
thal          2.0
Name: 107, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          45.0
sex           1.0
cp            0.0
trestbps    142.0
chol        309.0
fbs           0.0
restecg       0.0
thalach     147.0
exang         1.0
oldpeak       0.0
slope         1.0
ca            3.0
thal          3.0
Name: 255, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          59.0
sex           1.0
cp            3.0
trestbps    170.0
chol        288.0
fbs           0.0
restecg       0.0
thalach     159.0
exang         0.0
oldpeak       0.2
slope         1.0
ca            0.0
thal          3.0
Name: 228, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          63.0
sex           0.0
cp            0.0
trestbps    108.0
chol        269.0
fbs           0.0
restecg       1.0
thalach     169.0
exang         1.0
oldpeak       1.8
slope         1.0
ca            2.0
thal          2.0
Name: 263, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          49.0
sex           1.0
cp            2.0
trestbps    120.0
chol        188.0
fbs           0.0
restecg       1.0
thalach     139.0
exang         0.0
oldpeak       2.0
slope         1.0
ca            3.0
thal          3.0
Name: 208, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          66.0
sex           0.0
cp            3.0
trestbps    150.0
chol        226.0
fbs           0.0
restecg       1.0
thalach     114.0
exang         0.0
oldpeak       2.6
slope         0.0
ca            0.0
thal          2.0
Name: 17, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          57.0
sex           1.0
cp            0.0
trestbps    165.0
chol        289.0
fbs           1.0
restecg       0.0
thalach     124.0
exang         0.0
oldpeak       1.0
slope         1.0
ca            3.0
thal          3.0
Name: 231, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          52.0
sex           1.0
cp            1.0
trestbps    134.0
chol        201.0
fbs           0.0
restecg       1.0
thalach     158.0
exang         0.0
oldpeak       0.8
slope         2.0
ca            1.0
thal          2.0
Name: 55, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          51.0
sex           0.0
cp            2.0
trestbps    130.0
chol        256.0
fbs           0.0
restecg       0.0
thalach     149.0
exang         0.0
oldpeak       0.5
slope         2.0
ca            0.0
thal          2.0
Name: 50, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64
age          60.0
sex           0.0
cp            2.0
trestbps    120.0
chol        178.0
fbs           1.0
restecg       1.0
thalach      96.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          2.0
Name: 136, dtype: float64 age          54.0
sex           1.0
cp            0.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     160.0
exang         0.0
oldpeak       1.2
slope         2.0
ca            0.0
thal          2.0
Name: 10, dtype: float64

In [168]:
k = 5

In [169]:
kNN = [p[1] for p in sorted(knn())[:k]]

In [170]:
nOut = [df.iloc[np].target for np in kNN]

In [171]:
nOut

[1.0, 0.0, 0.0, 1.0, 1.0]

In [172]:
from collections import Counter
def mode(ls):
    return Counter(ls).most_common(1)[0][0]

In [173]:
mode(nOut)

1.0

In [174]:
test_y.iloc[i]

0

In [205]:
k = 5
for i in range(len(test_x)):
    kNN = [p[1] for p in sorted(knn())[:k]]
    nOut = [df.iloc[np].target for np in kNN]
    boolArr.append(test_y.iloc[i] == mode(nOut))
print(k, sum(boolArr)/ len(boolArr))

5 0.5849056603773585

In [206]:
for k in range(1,9):
    boolArr = []
    for i in range(len(test_x)):
        kNN = [p[1] for p in sorted(knn())[:k]]
        nOut = [df.iloc[np].target for np in kNN]
        #nOut
        boolArr.append(test_y.iloc[i] == mode(nOut))
    print(k, sum(boolArr)/ len(boolArr))

1 0.5849056603773585
2 0.5849056603773585
3 0.6415094339622641
4 0.6415094339622641
5 0.660377358490566
6 0.6981132075471698
7 0.6792452830188679
8 0.6792452830188679

so i got 67% accuracy When key =7